# 项目名称, 会用来向Jumpserver注册, 识别而已, 不能重复
# NAME: {{ Hostname }}

# Jumpserver项目的url, api请求注册会使用
CORE_HOST: http://127.0.0.1:8080

# Bootstrap Token, 预共享秘钥, 用来注册使用的service account和terminal
# 请和jumpserver 配置文件中保持一致，注册完成后可以删除
BOOTSTRAP_TOKEN: <PleasgeChangeSameWithJumpserver>

# 启动时绑定的ip, 默认 0.0.0.0
# BIND_HOST: 0.0.0.0

# 监听的HTTP/WS端口号，默认8081
# HTTPD_PORT: 8081

# 设置日志级别 [DEBUG, INFO, WARN, ERROR, FATAL, CRITICAL]
# LOG_LEVEL: INFO

# Guacamole Server ip， 默认127.0.0.1
# GUA_HOST: 127.0.0.1

# Guacamole Server 端口号，默认4822
# GUA_PORT: 4822

# 会话共享使用的类型 [local, redis], 默认local
# SHARE_ROOM_TYPE: local

# Redis配置
# REDIS_HOST: 127.0.0.1
# REDIS_PORT: 6379
# REDIS_PASSWORD:
# REDIS_DB_ROOM:

# 全局禁用上传下载
# JUMPSERVER_DISABLE_ALL_COPY_PASTE: false

# 全局禁用剪切板粘贴复制
# JUMPSERVER_DISABLE_ALL_UPLOAD_DOWNLOAD: false

# 开启Remote app的上传下载 ( 需 remote app 可打开文件系统 )
# JUMPSERVER_REMOTE_APP_UPLOAD_DOWNLOAD_ENABLE: false

# 开启Remote app的剪切板粘贴复制
# JUMPSERVER_REMOTE_APP_COPY_PASTE_ENABLE: false

# 定时清理挂载盘文件的时间间隔 (单位：小时)，如果设置值 0，则不清理。（ v2.13新增 ）
# JUMPSERVER_CLEAN_DRIVE_SCHEDULE_TIME: 1